In [7]:
!pip install yahoo_fin

Requirement already satisfied: yahoo_fin in /usr/local/lib/python3.10/dist-packages (0.8.9.1)
Requirement already satisfied: requests-html in /usr/local/lib/python3.10/dist-packages (from yahoo_fin) (0.10.0)
Requirement already satisfied: feedparser in /usr/local/lib/python3.10/dist-packages (from yahoo_fin) (6.0.10)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from yahoo_fin) (2.31.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from yahoo_fin) (1.5.3)
Requirement already satisfied: sgmllib3k in /usr/local/lib/python3.10/dist-packages (from feedparser->yahoo_fin) (1.0.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->yahoo_fin) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->yahoo_fin) (1.23.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->yahoo_fin) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->yahoo_fin) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->yahoo_fin) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->yahoo_fin) (2023.7.22)
Requirement already satisfied: pyquery in /usr/local/lib/python3.10/dist-packages (from requests-html->yahoo_fin) (2.0.0)
Requirement already satisfied: fake-useragent in /usr/local/lib/python3.10/dist-packages (from requests-html->yahoo_fin) (1.3.0)
Requirement already satisfied: parse in /usr/local/lib/python3.10/dist-packages (from requests-html->yahoo_fin) (1.19.1)
Requirement already satisfied: bs4 in /usr/local/lib/python3.10/dist-packages (from requests-html->yahoo_fin) (0.0.1)
Requirement already satisfied: w3lib in /usr/local/lib/python3.10/dist-packages (from requests-html->yahoo_fin) (2.1.2)
Requirement already satisfied: pyppeteer>=0.0.14 in /usr/local/lib/python3.10/dist-packages (from requests-html->yahoo_fin) (1.0.2)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (6.8.0)
Requirement already satisfied: pyee<9.0.0,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (8.2.2)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.66.1)
Requirement already satisfied: websockets<11.0,>=10.0 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (10.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->yahoo_fin) (1.16.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4->requests-html->yahoo_fin) (4.11.2)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.10/dist-packages (from pyquery->requests-html->yahoo_fin) (4.9.3)
Requirement already satisfied: cssselect>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from pyquery->requests-html->yahoo_fin) (1.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4->requests-html->yahoo_fin) (2.5)

## Import libraries

In [8]:
from yahoo_fin.stock_info import get_data
import pandas as pd
import numpy as np

## First, scrape latest 25 candles

In [9]:
latest_25_candles = get_data('GOOGL', index_as_date=False).tail(25)
latest_25_candles

,date,open,high,low,close,adjclose,volume,ticker
4822,2023-10-16,138.169998,139.630005,137.990005,139.100006,139.100006,28501900,GOOGL
4823,2023-10-17,138.630005,139.899994,137.179993,139.720001,139.720001,23515800,GOOGL
4824,2023-10-18,139.449997,140.720001,137.380005,137.960007,137.960007,23375000,GOOGL
4825,2023-10-19,138.500000,139.660004,137.380005,137.750000,137.750000,26066000,GOOGL
4826,2023-10-20,137.330002,137.869995,135.080002,135.600006,135.600006,26315200,GOOGL
4827,2023-10-23,135.039993,137.660004,133.949997,136.500000,136.500000,26317900,GOOGL
4828,2023-10-24,137.830002,139.360001,137.419998,138.809998,138.809998,44814300,GOOGL
4829,2023-10-25,128.160004,128.309998,125.070000,125.610001,125.610001,84366200,GOOGL
4830,2023-10-26,123.269997,124.330002,121.269997,122.279999,122.279999,57061100,GOOGL
4831,2023-10-27,122.879997,123.309998,120.209999,122.169998,122.169998,44566500,GOOGL
4832,2023-10-30,123.209999,125.400002,122.750000,124.459999,124.459999,28940100,GOOGL
4833,2023-10-31,125.059998,125.370003,122.690002,124.080002,124.080002,26292300,GOOGL
4834,2023-11-01,124.070000,126.489998,123.720001,126.449997,126.449997,30082400,GOOGL
4835,2023-11-02,128.419998,128.979996,126.930000,127.489998,127.489998,27124600,GOOGL
4836,2023-11-03,128.020004,129.529999,127.860001,129.100006,129.100006,26380100,GOOGL
4837,2023-11-06,129.050003,130.339996,128.669998,130.250000,130.250000,19052700,GOOGL
4838,2023-11-07,130.710007,131.910004,129.880005,130.970001,130.970001,29757300,GOOGL
4839,2023-11-08,130.970001,132.210007,130.779999,131.839996,131.839996,26425800,GOOGL
4840,2023-11-09,131.960007,132.550003,130.070007,130.240005,130.240005,23747800,GOOGL
4841,2023-11-10,130.100006,132.800003,129.410004,132.589996,132.589996,26913300,GOOGL
4842,2023-11-13,131.779999,132.589996,131.250000,132.089996,132.089996,18324800,GOOGL
4843,2023-11-14,134.190002,135.699997,133.320007,133.619995,133.619995,32395200,GOOGL
4844,2023-11-15,134.869995,135.029999,133.570007,134.619995,134.619995,23861500,GOOGL
4845,2023-11-16,135.190002,137.220001,134.320007,136.929993,136.929993,28013200,GOOGL
4846,2023-11-17,136.000000,136.059998,133.649994,135.309998,135.309998,37240600,GOOGL

## Drop adjusted close column

In [10]:
# Drop the adjusted close column
latest_25_candles = latest_25_candles.drop(['adjclose'], axis=1)

## Add necessary columns

In [11]:
# Get the selling pressure (i.e. distance between candle's high and close)
latest_25_candles['SellingPressure'] = latest_25_candles['high'] - latest_25_candles['close']

# Get the length of candle's body (from open to close)

latest_25_candles['O-to-C'] = latest_25_candles['close'] - latest_25_candles['open']

# Get the rolling mean of the candles' bodies for recent 20 candles

latest_25_candles['OC-20D-Mean'] = latest_25_candles['O-to-C'].rolling(20).mean()

# Get the % change of the current OC relative from the rolling mean

latest_25_candles['OC-%-from-20D-Mean'] = 100*(latest_25_candles['O-to-C'] - latest_25_candles['OC-20D-Mean'])/latest_25_candles['OC-20D-Mean']

# Get the maximum OC compared to the recent 10 candles

latest_25_candles['MaxOC_Prev10'] = latest_25_candles['O-to-C'].rolling(10).max()

# Get the rolling mean of volume for the recent 20 candles

latest_25_candles['Volume-20D-Mean'] = latest_25_candles['volume'].rolling(20).mean()

# Get the % change of the current volume relative from the rolling mean

latest_25_candles['Volume-%-from-20D-Mean'] = 100*(latest_25_candles['volume'] - latest_25_candles['Volume-20D-Mean'])/latest_25_candles['Volume-20D-Mean']

In [12]:
latest_25_candles

,date,open,high,low,close,volume,ticker,SellingPressure,O-to-C,OC-20D-Mean,OC-%-from-20D-Mean,MaxOC_Prev10,Volume-20D-Mean,Volume-%-from-20D-Mean
4822,2023-10-16,138.169998,139.630005,137.990005,139.100006,28501900,GOOGL,0.529999,0.930008,NaN,NaN,NaN,NaN,NaN
4823,2023-10-17,138.630005,139.899994,137.179993,139.720001,23515800,GOOGL,0.179993,1.089996,NaN,NaN,NaN,NaN,NaN
4824,2023-10-18,139.449997,140.720001,137.380005,137.960007,23375000,GOOGL,2.759995,-1.489990,NaN,NaN,NaN,NaN,NaN
4825,2023-10-19,138.500000,139.660004,137.380005,137.750000,26066000,GOOGL,1.910004,-0.750000,NaN,NaN,NaN,NaN,NaN
4826,2023-10-20,137.330002,137.869995,135.080002,135.600006,26315200,GOOGL,2.269989,-1.729996,NaN,NaN,NaN,NaN,NaN
4827,2023-10-23,135.039993,137.660004,133.949997,136.500000,26317900,GOOGL,1.160004,1.460007,NaN,NaN,NaN,NaN,NaN
4828,2023-10-24,137.830002,139.360001,137.419998,138.809998,44814300,GOOGL,0.550003,0.979996,NaN,NaN,NaN,NaN,NaN
4829,2023-10-25,128.160004,128.309998,125.070000,125.610001,84366200,GOOGL,2.699997,-2.550003,NaN,NaN,NaN,NaN,NaN
4830,2023-10-26,123.269997,124.330002,121.269997,122.279999,57061100,GOOGL,2.050003,-0.989998,NaN,NaN,NaN,NaN,NaN
4831,2023-10-27,122.879997,123.309998,120.209999,122.169998,44566500,GOOGL,1.139999,-0.709999,NaN,NaN,1.460007,NaN,NaN
4832,2023-10-30,123.209999,125.400002,122.750000,124.459999,28940100,GOOGL,0.940002,1.250000,NaN,NaN,1.460007,NaN,NaN
4833,2023-10-31,125.059998,125.370003,122.690002,124.080002,26292300,GOOGL,1.290001,-0.979996,NaN,NaN,1.460007,NaN,NaN
4834,2023-11-01,124.070000,126.489998,123.720001,126.449997,30082400,GOOGL,0.040001,2.379997,NaN,NaN,2.379997,NaN,NaN
4835,2023-11-02,128.419998,128.979996,126.930000,127.489998,27124600,GOOGL,1.489998,-0.930000,NaN,NaN,2.379997,NaN,NaN
4836,2023-11-03,128.020004,129.529999,127.860001,129.100006,26380100,GOOGL,0.429993,1.080002,NaN,NaN,2.379997,NaN,NaN
4837,2023-11-06,129.050003,130.339996,128.669998,130.250000,19052700,GOOGL,0.089996,1.199997,NaN,NaN,2.379997,NaN,NaN
4838,2023-11-07,130.710007,131.910004,129.880005,130.970001,29757300,GOOGL,0.940002,0.259995,NaN,NaN,2.379997,NaN,NaN
4839,2023-11-08,130.970001,132.210007,130.779999,131.839996,26425800,GOOGL,0.370010,0.869995,NaN,NaN,2.379997,NaN,NaN
4840,2023-11-09,131.960007,132.550003,130.070007,130.240005,23747800,GOOGL,2.309998,-1.720001,NaN,NaN,2.379997,NaN,NaN
4841,2023-11-10,130.100006,132.800003,129.410004,132.589996,26913300,GOOGL,0.210007,2.489990,0.107000,2227.094341,2.489990,32480815.0,-17.140934
4842,2023-11-13,131.779999,132.589996,131.250000,132.089996,18324800,GOOGL,0.500000,0.309998,0.075999,307.894473,2.489990,31971960.0,-42.684778
4843,2023-11-14,134.190002,135.699997,133.320007,133.619995,32395200,GOOGL,2.080002,-0.570007,-0.007001,8042.109852,2.489990,32415930.0,-0.063950
4844,2023-11-15,134.869995,135.029999,133.570007,134.619995,23861500,GOOGL,0.410004,-0.250000,0.054999,-554.555543,2.489990,32440255.0,-26.444783
4845,2023-11-16,135.190002,137.220001,134.320007,136.929993,28013200,GOOGL,0.290009,1.739990,0.179498,869.363120,2.489990,32537615.0,-13.905183
4846,2023-11-17,136.000000,136.059998,133.649994,135.309998,37240600,GOOGL,0.750000,-0.690002,0.231498,-398.059843,2.489990,33083885.0,12.564168

## Get only the latest 5 rows (candles) from our dataframe

In [13]:
latest_5_candles = latest_25_candles.tail(5)
latest_5_candles

,date,open,high,low,close,volume,ticker,SellingPressure,O-to-C,OC-20D-Mean,OC-%-from-20D-Mean,MaxOC_Prev10,Volume-20D-Mean,Volume-%-from-20D-Mean
4842,2023-11-13,131.779999,132.589996,131.250000,132.089996,18324800,GOOGL,0.500000,0.309998,0.075999,307.894473,2.48999,31971960.0,-42.684778
4843,2023-11-14,134.190002,135.699997,133.320007,133.619995,32395200,GOOGL,2.080002,-0.570007,-0.007001,8042.109852,2.48999,32415930.0,-0.063950
4844,2023-11-15,134.869995,135.029999,133.570007,134.619995,23861500,GOOGL,0.410004,-0.250000,0.054999,-554.555543,2.48999,32440255.0,-26.444783
4845,2023-11-16,135.190002,137.220001,134.320007,136.929993,28013200,GOOGL,0.290009,1.739990,0.179498,869.363120,2.48999,32537615.0,-13.905183
4846,2023-11-17,136.000000,136.059998,133.649994,135.309998,37240600,GOOGL,0.750000,-0.690002,0.231498,-398.059843,2.48999,33083885.0,12.564168

## Screen the latest 5 rows if there is any breakout

In [21]:
condition = (latest_5_candles['O-to-C'] >= 0.0) & (latest_5_candles['O-to-C'] == latest_5_candles['MaxOC_Prev10']) & (latest_5_candles['SellingPressure']/latest_5_candles['O-to-C'] <= 0.40) & (latest_5_candles['OC-%-from-20D-Mean'] >= 100.0) & (latest_5_candles['Volume-%-from-20D-Mean'] >= 50.0)

breakouts = latest_5_candles[condition].reset_index(drop=True)

breakouts

Empty DataFrame
Columns: [date, open, high, low, close, volume, ticker, SellingPressure, O-to-C, OC-20D-Mean, OC-%-from-20D-Mean, MaxOC_Prev10, Volume-20D-Mean, Volume-%-from-20D-Mean]
Index: []

In [ ]:
if len(breakouts) > 0:
  print(breakouts.loc[0, 'ticker'])

## Putting all codes in one function

NOTE: The function accomodates a recent minimum average volume.

In [1]:
def breakouts_screener(stocks, min_ave_volume):
  '''A function that accepts a list of stocks and returns (as a list) only the stocks that had at least one breakout candle in the past 5 days'''
  '''Libraries that must be installed: yahoo_fin, pandas, and numpy '''

  screened_stocks = []

  # Analyze each stock in the provided list
  for ticker in stocks:
    try:
      ## SCRAPE THE LATEST 25 CANDLES
      latest_25_candles = get_data(ticker, index_as_date=False).tail(25)

      # Drop the adjusted close column
      latest_25_candles = latest_25_candles.drop(['adjclose'], axis=1)

      ## ADD NECESSARY COLUMNS
      # Get the selling pressure (i.e. distance between candle's high and close)

      latest_25_candles['SellingPressure'] = latest_25_candles['high'] - latest_25_candles['close']

      # Get the length of candle's body (from open to close)

      latest_25_candles['O-to-C'] = latest_25_candles['close'] - latest_25_candles['open']

      # Get the rolling mean of the candles' bodies for recent 20 candles

      latest_25_candles['OC-20D-Mean'] = latest_25_candles['O-to-C'].rolling(20).mean()

      # Get the % change of the current OC relative from the rolling mean

      latest_25_candles['OC-%-from-20D-Mean'] = 100*(latest_25_candles['O-to-C'] - latest_25_candles['OC-20D-Mean'])/latest_25_candles['OC-20D-Mean']

      # Get the maximum OC compared to the recent 10 candles

      latest_25_candles['MaxOC_Prev10'] = latest_25_candles['O-to-C'].rolling(10).max()

      # Get the rolling mean of volume for the recent 20 candles

      latest_25_candles['Volume-20D-Mean'] = latest_25_candles['volume'].rolling(20).mean()

      # Get the % change of the current volume relative from the rolling mean

      latest_25_candles['Volume-%-from-20D-Mean'] = 100*(latest_25_candles['volume'] - latest_25_candles['Volume-20D-Mean'])/latest_25_candles['Volume-20D-Mean']

      ## GET ONLY THE LATEST 5 CANDLES FOR SCREENING
      latest_5_candles = latest_25_candles.tail(5)

      # Select only the rows for breakout candles
      condition = (latest_5_candles['O-to-C'] >= 0.0) & (latest_5_candles['O-to-C'] == latest_5_candles['MaxOC_Prev10']) & (latest_5_candles['SellingPressure']/latest_5_candles['O-to-C'] <= 0.40) & (latest_5_candles['OC-%-from-20D-Mean'] >= 100.0) & (latest_5_candles['Volume-%-from-20D-Mean'] >= 50.0)
      breakouts = latest_5_candles[condition].reset_index(drop=True)

      ## SCREENER: SAVE THE TICKER SYMBOL IF THE STOCK HAD ANY BREAKOUT IN THE PAST 5 DAYS

      ave_volume = latest_5_candles['volume'].mean()

      if len(breakouts) > 0 and ave_volume >= min_ave_volume:
        ticker = breakouts.loc[0, 'ticker']
        screened_stocks.append(ticker)

    except Exception:
      continue

  ## CODE THE OUTPUT OF THE FUNCTION
  if len(screened_stocks) == 0:
    output = f"No stocks from the provided list with recent minimum average volume of {min_ave_volume} shares showed any breakout candle in the past 5 days."
    return output

  elif len(screened_stocks) > 0:
    output = f"The stock/s with at least one breakout candle in the past 5 days is/are {screened_stocks}."
    return output

## Use the `breakouts_screener(ticker, min_ave_volume)` function

In [16]:
# Access wiki page for S&P 500 stocks using pd.read_html() method
# The result of the following codes is lists of dataframes

url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
sp500_wiki = pd.read_html(url)

In [17]:
# Get the our desired dataframe for S&P 500

sp500_df = sp500_wiki[0]
sp500_df

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
499,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
500,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
501,ZION,Zions Bancorporation,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [18]:
# Get only the stock symbols and save them in a list object

sp500_symbols_list = sp500_df['Symbol'].tolist()
print('Number of stock symbols: ', len(sp500_symbols_list))

# Print the first 20 symbols in our list
sp500_symbols_list[:20]

Number of stock symbols:  503

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADM',
 'ADBE',
 'ADP',
 'AES',
 'AFL',
 'A',
 'ABNB',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT']

In [19]:
my_list = ['AAPL', 'MSFT', 'GOOGL']

breakouts_screener(stocks=my_list, min_ave_volume=100000)

'No stocks from the provided list with recent minimum average volume of 100000 shares showed any breakout candle in the past 5 days.'

In [20]:
breakouts_screener(stocks=sp500_symbols_list, min_ave_volume=100000)

/usr/local/lib/python3.10/dist-packages/yahoo_fin/stock_info.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame['ticker'] = ticker.upper()
/usr/local/lib/python3.10/dist-packages/yahoo_fin/stock_info.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame['ticker'] = ticker.upper()
/usr/local/lib/python3.10/dist-packages/yahoo_fin/stock_info.py:116: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame['ticker'] = ticker.upper()

"The stock/s with at least one breakout candle in the past 5 days is/are ['AMAT', 'BLK', 'CPB', 'GIS', 'HWM', 'INTC', 'TGT', 'ULTA']."